In [1]:
import pandas as pd
import numpy as np
a=pd.read_csv("data.csv")
a

,S.No,ID No,Name of the Student,Class,Mail Id,Placed/Not (Yes/No),Company Names,Any Reason (Higher Studies/GOVT Jobs)
0,1,S160884,Reddi.Kumar,CSE -4F,S160884@rguktsklm.ac.in,Yes,"Swipe, TCS, Tricon infotech",NaN
1,2,S160849,Peketi siva sankar,CSE -4F,S160849@rguktsklm.ac.in,Yes,"Wipro, Tricon infotech",NaN
2,3,S161000,P.v.b.g.Sharma,CSE -4F,S161000@rguktsklm.ac.in,Yes,Westward labs,NaN
3,4,S160931,YATAM RAMESH THRINADH,CSE -4F,S160931@rguktsklm.ac.in,Yes,"Capgemini, Wipro",NaN
4,5,S160196,Gadu Appala Naidu,CSE -4F,S160196@rguktsklm.ac.in,yes,Candid Reviews,NaN
5,6,S160404,Netheti Siva Ram Krishna,CSE -4F,S160404@rguktsklm.ac.in,Yes,Altimetrik,NaN
6,7,S160401,Bolisetty Naga Venkata Manoj,CSE -4F,S160401@rguktsklm.ac.in,yes,"Swipe, Raja software labs, TCS, Capgemini",NaN
7,8,S160296,Bakkamanthula Hari Krishna,CSE -4F,S160296@rguktsklm.ac.in,yes,"TCS,Wipro",NaN
8,9,S160132,V.S.N.V.Mohan,CSE -4F,S160132@rguktsklm.ac.in,Yes,"Point Motion Inc., Intain Fintech, IESoftek.",NaN
9,10,S160273,B.Prasad,CSE -4F,S160273@rguktsklm.ac.in,yes,"Wipro, Capgemini, Intain technologies",NaN
10,11,S160542,K.Sathvik,CSE -4F,S160542@rguktsklm.ac.in,yes,Wipro,NaN
11,12,S160559,D.jagannadhrao,CSE -4F,S160559@rguktsklm.ac.in,Yes,Capgemini,NaN
12,13,S161105,Gandavarapu.Ramesh,CSE -4F,S161105@rguktsklm.ac.in,yes,"Wipro,Infosys",NaN
13,14,S160896,K.V.V.S.N Reddy,CSE -4F,S160896@rguktsklm.ac.in,yes,"Capgemini, Infosys, Wipro",NaN
14,15,S160589,Pidugu.Maa Sai Venkata Dinesh,CSE -4F,S160589@rguktsklm.ac.in,yes,"tcs, wipro",NaN
15,16,S160344,G.Pavan Kumar,CSE -4F,S160344@rguktsklm.ac.in,yes,hexaware,NaN
16,17,S160179,H.Praveen kumar,CSE -4F,S160179@rguktsklm.ac.in,yes,Hexaware,NaN
17,18,S160862,SOMASANI.JAYA SUPRIYA,CSE -4F,S160862@rguktsklm.ac.in,yes,Nspira,NaN
18,19,S160997,Paruchuri.Kathyayini,CSE -4F,S160997@rguktsklm.ac.in,Yes,Wipro,NaN
19,20,S160879,Talluri.Sai Durga,CSE -4F,S160879@rguktsklm.ac.in,Yes,"Capgemini, wipro",NaN
20,21,S160806,NALLA.LAKSHMI KUMARI,CSE -4F,S160806@rguktsklm.ac.in,Yes,"Infosys, Capgemini",NaN
21,22,S160836,Ede Supriya,CSE -4F,S160836@rguktsklm.ac.in,Yes,wipro,NaN
22,23,S160657,LAKSHMI TULASI CHITTELA,CSE -4F,S160657@rguktsklm.ac.in,Yes,Wipro,NaN
23,24,S160421,GOLLA.VENKATA RADHA,CSE -4F,S160421@rguktsklm.ac.in,Yes,Capgemini,NaN
24,25,S160619,Kanchipati.Uma Maheswari,CSE -4F,S160619@rguktsklm.ac.in,Yes,Capgemini,NaN
25,26,S160274,Amireddy Syamala,CSE -4F,S160274@rguktsklm.ac.in,Yes,Capgemini,NaN
26,27,S160505,Nizampatnam. sowjanya,CSE -4F,S160505@rguktsklm.ac.in,Yes,"Wipro,Capgemini,Mindtree",NaN
27,28,S160314,Chaganti.Kavya Sri,CSE -4F,S160314@rguktsklm.ac.in,Yes,"TCS, Capgemini, Wipro",NaN
28,29,s160394,Lakshmmi Kosuri,CSE -4F,s160394@rguktsklm.ac.in,No,NaN,Civils Aspirant
29,30,S160907,Mugada Jhansi Rani,CSE -4F,S160907@rguktsklm.ac.in,No,NaN,NP
30,31,S160851,KOMIRISETTI SRILAKSHMI,CSE -4F,S160851@rguktsklm.ac.in,Yes,"TCS, Capgemini, HashedIn by Deloitte",NaN
31,32,S160485,Uriti Pavani,CSE -4F,S160485@rguktsklm.ac.in,Yes,Nagarro,NaN
32,33,S160956,Kaki Baby Varalakshmi Bhavani,CSE -4F,S160956@rguktsklm.ac.in,yes,Capgemini,NaN
33,34,S160727,Battu.Jahnavi,CSE -4F,S160727@rguktsklm.ac.in,No,Waiting for infosys results,NP
34,35,S160773,Pentapati Vijaya Lakshmi Durga Devi,CSE -4F,S160773@rguktsklm.ac.in,yes,"Wipro,Tcs",NaN
35,36,s160587,kommula swetha,CSE -4F,s160587@rguktsklm.ac.in,Yes,Capgemini,NaN
36,37,S160431,Rallapalli Kalyani,CSE -4F,S160431@rguktsklm.ac.in,yes,TCS,NaN
37,38,S160646,Pandi Anusha,CSE -4F,S160646@rguktsklm.ac.in,yes,"Infosys, capgemini",NaN
38,39,S160144,Sappati Praveena,CSE -4F,S160144@rguktsklm.ac.in,yes,TCS Digital,NaN
39,40,S160266,Gogula Triveni,CSE -4F,S160266@rguktsklm.ac.in,Yes,Wipro,NaN
40,41,S160446,Balineni kavya,CSE -4F,S160446@rguktsklm.ac.in,Yes,"Wipro, Infosys",NaN
41,42,s160355,RESHMA GANTA,CSE -4F,s160355@rguktsklm.ac.in,Yes,"Capgemini, Infosys, Wipro",NaN
42,43,s160408,Rajyalakshmi gonaboina,CSE -4F,s160408@rguktsklm.ac.in,No,Infosys interview pending,NP
43,44,s160507,chilakala sravani,CSE -4F,s160507@rguktsklm.ac.in,Yes,"Lumen, capgemini, west Agile",NaN
44,45,s160747,Peddireddy madhavi,CSE -4F,s160747@rguktsklm.ac.in,Yes,"RapidKen.AI, Arachnomesh Technologies",NaN
45,46,S160609,Gali Anjali,CSE -4F,S160609@rguktsklm.ac.in,Yes,"Capgemini, Wipro",NaN
46,47,s160290,Yaradi Rasi,CSE -4F,s160290@rguktsklm.ac.in,yes,Infosys,NaN
47,48,s160282,Medida siva nageswari,CSE -4F,s160282@rguktsklm.ac.in,Yes,Infosys,NaN
48,49,s160302,Peketi.Anusha,CSE -4F,s160302@rguktsklm.ac.in,yes,Infosys,NaN
49,50,s160720,Banala pavithra,CSE -4F,s160720@rguktsklm.ac.in,Yes,Infosys,NaN
50,51,S160845,Madabathula.Bala,CSE -4F,S160845@rguktsklm.ac.in,Yes,"Capgemini, Wipro, Hexaware, Atos Syntel",NaN
51,52,S160175,satyakala.setti,CSE -4F,S160175@rguktsklm.ac.in,No,NaN,Civils Aspirant
52,53,S161061,Lam.Akshara Mythili,CSE -4F,S161061@rguktsklm.ac.in,Yes,Purple Talk,NaN
53,54,s160322,kunda sri lakshmi lavanya,CSE -4F,s160322@rguktsklm.ac.in,yes,"wipro, capgemini",NaN
54,55,s160161,koila leelavathi,CSE -4F,s160161@rguktsklm.ac.in,yes,wipro,NaN
55,56,S160917,Inti.Naga sivani vaishnavi bodhitha,CSE -4F,S160917@rguktsklm.ac.in,Yes,"Hexaware, Infosys",NaN
56,57,S160032,Iggirala.Ramyasri,CSE -4F,S160032@rguktsklm.ac.in,Yes,Wipro,NaN
57,58,S160497,Munduri.Jyothi Jahnavi,CSE -4F,S160497@rguktsklm.ac.in,Yes,"TCS, Infosys",NaN

In [2]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 8 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   S.No                                   58 non-null     int64
 1   ID No                                  58 non-null     object
 2   Name of the Student                    58 non-null     object
 3   Class                                  58 non-null     object
 4   Mail Id                                58 non-null     object
 5   Placed/Not (Yes/No)                    58 non-null     object
 6   Company Names                          55 non-null     object
 7   Any Reason (Higher Studies/GOVT Jobs)  5 non-null      object
dtypes: int64(1), object(7)
memory usage: 3.8+ KB

In [5]:
a.describe()

            S.No
count  58.000000
mean   29.500000
std    16.886879
min     1.000000
25%    15.250000
50%    29.500000
75%    43.750000
max    58.000000

In [12]:
a["Name of the Student"